volumes:
  langgraph-data:
    driver: local
services:
  lightrag-api:
    build:
      context: ../lightrag-pinecone
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9621}:9621"
    env_file:
      - ../lightrag-pinecone/.env
    environment:
      - TZ=UTC
    volumes:
      - ../lightrag-pinecone/data/rag_storage:/app/data/rag_storage
      - ../lightrag-pinecone/data/inputs:/app/data/inputs
  fastapi-wrapper:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      langgraph-api:
        condition: service_healthy
    env_file:
      - .env
    environment:
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGGRAPH_API_URL: http://langgraph-api:8000
    volumes:
      - ./src:/app/src

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      fastapi-wrapper:
        condition: service_started
    env_file:
      - .env
    environment:
      FASTAPI_URL: http://fastapi-wrapper:8000
    volumes:
      - ./src:/app/src
