FROM langchain/langgraph-api:3.11



ADD . /deps/react-agent

RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*

ENV LANGSERVE_GRAPHS='{"agent": "/deps/react-agent/src/react_agent/graph.py:graph"}'

WORKDIR /deps/react-agent