# fly.toml app configuration file generated for ghostwriter-fastapi on 2025-01-31T00:02:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghostwriter-fastapi'
primary_region = 'atl'

[build]
  dockerfile = 'Dockerfile.fastapi'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
