cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: admin123
pre-authorized:
  emails:
    - admin@example.com
